/** Entry point: loads assets, shows the title screen, starts games. */
import { Menus } from './ui/menus.ts';
import { applyGuiScale } from './ui/dom.ts';
import { isTouchDevice } from './ui/touch.ts';
import { SaveManager, loadOptions, saveOptions, type Options, type WorldMeta } from './core/save.ts';
import { loadAtlas, type LoadedAtlas } from './render/atlas.ts';
import type { ModelsJson } from './world/models.ts';
import type { PoolEntry, StructureIndexEntry, TemplateJson } from './world/gen/structures.ts';
import type { StructureBundle } from './world/protocol.ts';
import { Game } from './core/game.ts';
import { parseSeed } from './core/rng.ts';
import { biomes } from './world/biomes.ts';
import { blocks } from './blocks/registry.ts';
import { items } from './items/registry.ts';


const BASE = import.meta.env.BASE_URL;

async function main() {
  const app = document.getElementById('app')!;
  const save = new SaveManager();
  const options: Options = loadOptions();
  if (isTouchDevice()) phoneSetup();
  applyGuiScale(options.guiScale);
  // Auto follows the window, so it has to be worked out again whenever the window changes shape
  window.addEventListener('resize', () => applyGuiScale(options.guiScale));
  let game: Game | null = null;
  let assets: { blocks: LoadedAtlas; items: LoadedAtlas; models: ModelsJson; structures: StructureBundle } | null = null;

  const menus = new Menus(app, {
    listWorlds: () => save.listWorlds(),
    onPlay: (meta) => void startGame(meta),
    onCreate: async (name, seedText, gamemode) => {
      const meta = await save.createWorld(name, parseSeed(seedText), seedText, gamemode);
      await startGame(meta);
    },
    onDelete: (meta) => save.deleteWorld(meta.id),
    onExport: async (meta) => {
      const blob = await save.exportWorld(meta.id);
      const a = document.createElement('a');
      a.href = URL.createObjectURL(blob);
      a.download = `${meta.name.replace(/[^a-z0-9_-]+/gi, '_') || 'world'}.zip`;
      a.click();
      setTimeout(() => URL.revokeObjectURL(a.href), 5000);
    },
    onImport: async (file) => {
      try {
        await save.importWorld(await file.arrayBuffer());
      } catch (e) {
        alert(`Import failed: ${(e as Error).message}`);
      }
    },
    onResume: () => game?.resume(),
    onQuitToTitle: () => void quitToTitle(),
    onOptionsChanged: (o) => {
      saveOptions(o);
      applyGuiScale(o.guiScale);
      game?.applyOptions(o);
    },
    onRespawn: () => game?.respawn(),
  }, options);

  /** Vanilla structure templates, generated by `npm run structures`; the world runs without them. */
  async function loadStructures(base: string): Promise<StructureBundle> {
    try {
      const index = await fetch(`${base}structures/index.json`).then((r) => (r.ok ? (r.json() as Promise<StructureIndexEntry[]>) : null));
      if (!index) return { index: [], templates: {}, pools: {} };
      const templates: Record<string, TemplateJson> = {};
      const pools: Record<string, Record<string, PoolEntry[]>> = {};
      await Promise.all(index.map(async (entry) => {
        if (!entry.pieces.length) return; // structures built in code (mineshafts) ship no templates
        const r = await fetch(`${base}structures/${entry.name}.json`);
        if (!r.ok) return;
        const bundle = (await r.json()) as { pieces: Record<string, TemplateJson>; pools?: Record<string, PoolEntry[]> };
        Object.assign(templates, bundle.pieces);
        if (bundle.pools) pools[entry.name] = bundle.pools;
      }));
      return { index, templates, pools };
    } catch {
      return { index: [], templates: {}, pools: {} };
    }
  }

  async function loadAssets() {
    if (assets) return assets;
    menus.showLoading('Loading textures...', 0.1);
    const [b, i, models, structures] = await Promise.all([
      loadAtlas(BASE, 'blocks'),
      loadAtlas(BASE, 'items'),
      fetch(`${BASE}models.json`).then((r) => {
        if (!r.ok) throw new Error('models.json missing – run `npm run assets`');
        return r.json() as Promise<ModelsJson>;
      }),
      loadStructures(BASE),
    ]);
    assets = { blocks: b, items: i, models, structures };
    menus.hideLoading();
    return assets;
  }

  async function startGame(meta: WorldMeta) {
    const a = await loadAssets();
    menus.hide();
    menus.showLoading('Building terrain...', 0);
    game = new Game({ container: app, assets: a, save, meta, options, menus });
    (window as unknown as { voxelcraft: unknown }).voxelcraft = { game, blocks, items, biomes };
    await game.start((text, p) => menus.showLoading(text, p));
    menus.hideLoading();
  }

  async function quitToTitle() {
    if (game) {
      menus.showLoading('Saving world...', 0.5);
      await game.quit();
      game = null;
      menus.hideLoading();
    }
    menus.showTitle();
  }

  try {
    await loadAssets();
    menus.showTitle();
  } catch (e) {
    menus.showLoading(`Failed to load assets: ${(e as Error).message}`, 0);
    console.error(e);
  }
}

/**
 * What a phone needs that a desktop does not: the page marked as a touch one so the stylesheet can
 * lay out its controls, a nudge to turn the phone sideways, and a first tap that asks for the whole
 * screen. Both of the last two are best-effort — iOS grants neither to a page in Safari, which is
 * what the home-screen install in the manifest is for.
 */
function phoneSetup(): void {
  document.documentElement.classList.add('touch');
  const rotate = document.getElementById('rotate');
  const check = () => rotate?.classList.toggle('on', window.innerHeight > window.innerWidth);
  check();
  window.addEventListener('resize', check);
  window.addEventListener('orientationchange', check);
  const goFullscreen = () => {
    if (!document.fullscreenElement) void document.documentElement.requestFullscreen?.().catch(() => {});
    const orientation = screen.orientation as (ScreenOrientation & { lock?: (o: string) => Promise<void> }) | undefined;
    void orientation?.lock?.('landscape').catch(() => {});
  };
  window.addEventListener('pointerdown', goFullscreen, { once: true });
  // a double tap zooms a page by default, which on a game means the world jumps under the thumb
  document.addEventListener('gesturestart', (e) => e.preventDefault());
  document.addEventListener('dblclick', (e) => e.preventDefault());
}

void main();
