/** Entry point: loads assets, shows the title screen, starts games. */
import { Menus } from './ui/menus.ts';
import { SaveManager, loadOptions, saveOptions, type Options, type WorldMeta } from './core/save.ts';
import { loadAtlas, type LoadedAtlas } from './render/atlas.ts';
import type { ModelsJson } from './world/models.ts';
import type { StructureIndexEntry, TemplateJson } from './world/gen/structures.ts';
import { Game } from './core/game.ts';
import { parseSeed } from './core/rng.ts';
import { blocks } from './blocks/registry.ts';
import { items } from './items/registry.ts';

/** Structure templates and their spreads, passed to the world workers at init. */
export interface StructureBundle { index: StructureIndexEntry[]; templates: Record<string, TemplateJson> }

const BASE = import.meta.env.BASE_URL;

async function main() {
  const app = document.getElementById('app')!;
  const save = new SaveManager();
  const options: Options = loadOptions();
  document.documentElement.style.setProperty('--gui', String(options.guiScale));
  let game: Game | null = null;
  let assets: { blocks: LoadedAtlas; items: LoadedAtlas; models: ModelsJson; structures: StructureBundle } | null = null;

  const menus = new Menus(app, {
    listWorlds: () => save.listWorlds(),
    onPlay: (meta) => void startGame(meta),
    onCreate: async (name, seedText, gamemode) => {
      const meta = await save.createWorld(name, parseSeed(seedText), seedText, gamemode);
      await startGame(meta);
    },
    onDelete: (meta) => save.deleteWorld(meta.id),
    onExport: async (meta) => {
      const blob = await save.exportWorld(meta.id);
      const a = document.createElement('a');
      a.href = URL.createObjectURL(blob);
      a.download = `${meta.name.replace(/[^a-z0-9_-]+/gi, '_') || 'world'}.zip`;
      a.click();
      setTimeout(() => URL.revokeObjectURL(a.href), 5000);
    },
    onImport: async (file) => {
      try {
        await save.importWorld(await file.arrayBuffer());
      } catch (e) {
        alert(`Import failed: ${(e as Error).message}`);
      }
    },
    onResume: () => game?.resume(),
    onQuitToTitle: () => void quitToTitle(),
    onOptionsChanged: (o) => {
      saveOptions(o);
      document.documentElement.style.setProperty('--gui', String(o.guiScale));
      game?.applyOptions(o);
    },
    onRespawn: () => game?.respawn(),
  }, options);

  /** Vanilla structure templates, generated by `npm run structures`; the world runs without them. */
  async function loadStructures(base: string): Promise<StructureBundle> {
    try {
      const index = await fetch(`${base}structures/index.json`).then((r) => (r.ok ? (r.json() as Promise<StructureIndexEntry[]>) : null));
      if (!index) return { index: [], templates: {} };
      const templates: Record<string, TemplateJson> = {};
      await Promise.all(index.flatMap((e) => e.pieces).map(async (piece) => {
        const r = await fetch(`${base}structures/${piece}.json`);
        if (r.ok) templates[piece] = (await r.json()) as TemplateJson;
      }));
      return { index, templates };
    } catch {
      return { index: [], templates: {} };
    }
  }

  async function loadAssets() {
    if (assets) return assets;
    menus.showLoading('Loading textures...', 0.1);
    const [b, i, models, structures] = await Promise.all([
      loadAtlas(BASE, 'blocks'),
      loadAtlas(BASE, 'items'),
      fetch(`${BASE}models.json`).then((r) => {
        if (!r.ok) throw new Error('models.json missing – run `npm run assets`');
        return r.json() as Promise<ModelsJson>;
      }),
      loadStructures(BASE),
    ]);
    assets = { blocks: b, items: i, models, structures };
    menus.hideLoading();
    return assets;
  }

  async function startGame(meta: WorldMeta) {
    const a = await loadAssets();
    menus.hide();
    menus.showLoading('Building terrain...', 0);
    game = new Game({ container: app, assets: a, save, meta, options, menus });
    (window as unknown as { voxelcraft: unknown }).voxelcraft = { game, blocks, items };
    await game.start((text, p) => menus.showLoading(text, p));
    menus.hideLoading();
  }

  async function quitToTitle() {
    if (game) {
      menus.showLoading('Saving world...', 0.5);
      await game.quit();
      game = null;
      menus.hideLoading();
    }
    menus.showTitle();
  }

  try {
    await loadAssets();
    menus.showTitle();
  } catch (e) {
    menus.showLoading(`Failed to load assets: ${(e as Error).message}`, 0);
    console.error(e);
  }
}

void main();
