"""Optional TTS stage (tts.bat): type a line, get several GLaDOS takes.

  tts.bat                                   build (or resume building) the TTS model
  tts.bat "Oh. It's you."                   5 takes of that line
  tts.bat "Line one" "Line two" --takes 8
  tts.bat --file lines.txt                  one line per row
  tts.bat "..." --steps 0.6                 GLaDOS-mode steps on the RVC pass

Building (first run, resumable like run.bat):
  1. transcripts: the game's own captions for each clean line, checked against
     Whisper; where they disagree (or there is no caption) Whisper's text is used
  2. an F5-TTS fine-tuning set from the clean training lines (held-out lines stay out)
  3. fine-tune F5-TTS (bf16, 8-bit Adam, sized for 8 GB; smaller batches on out-of-memory)
  4. pick the best checkpoint by synthesising the held-out lines' text and scoring
     intelligibility (Whisper word error rate) and timbre against her real held-out lines;
     the untuned base model competes too, so fine-tuning can't make things worse

Speaking: each take is generated by F5-TTS, then run through the RVC model (pitch 0: it's
already her voice; RVC tightens the timbre), then ranked by word errors and timbre. Every
take is kept; <line>_best.wav is the top one and <line>_all_takes.wav plays them in rank order.
Recorded/typed lines only: this cannot run live inside voice.ai.
"""

from __future__ import annotations

import argparse
import csv
import datetime as _dt
import difflib
import math
import os
import re
import shutil
import threading
import time
from pathlib import Path

import numpy as np

from . import applio as AP
from . import audio as A
from . import evaluate as EV
from . import voice as V
from .captions import read_game_captions
from .common import (LOG, Blocked, State, StepFailed, Workspace, child_env, disk_free_gb, fmt_duration, now,
                     read_json, run, setup_logging, write_json)

F5_VERSION = "1.1.22"
ASR_MODEL = "openai/whisper-large-v3-turbo"
SIDE = Path(__file__).parent / "tts_side"
STEPS = [
    ("tts_setup", "Install F5-TTS in its own venv"),
    ("tts_transcripts", "Transcripts: game captions checked by Whisper"),
    ("tts_dataset", "Write the F5-TTS fine-tuning set"),
    ("tts_train", "Fine-tune F5-TTS on her clean lines"),
    ("tts_select", "Pick the best TTS checkpoint on held-out lines"),
]


# ----------------------------------------------------------------------------- helpers

def tts_python(ws: Workspace) -> Path:
    v = ws.env / "tts"
    return v / "Scripts" / "python.exe" if os.name == "nt" else v / "bin" / "python"


def tts_env(ws: Workspace, gpu: dict, workers: int = 4) -> dict:
    extra = {"HF_HOME": str(ws.tools / "hf-cache"), "GLADOS_TTS_WORKERS": str(workers),
             "TOKENIZERS_PARALLELISM": "false", "WANDB_MODE": "disabled"}
    if gpu.get("device") == "cuda":
        extra.update(CUDA_DEVICE_ORDER="PCI_BUS_ID", CUDA_VISIBLE_DEVICES=gpu["cuda_visible_devices"],
                     ACCELERATE_MIXED_PRECISION="bf16")
    else:
        extra.update(CUDA_VISIBLE_DEVICES="", ACCELERATE_MIXED_PRECISION="no")
    return child_env(extra)


def side(ws: Workspace, gpu: dict, script: str, *args, log_name="tts.log", on_line=None, check=True, workers=4):
    return run([tts_python(ws), SIDE / script, *args], cwd=ws.root, env=tts_env(ws, gpu, workers),
               log_name=log_name, logs_dir=ws.logs, on_line=on_line, check=check)


def words(text: str) -> list[str]:
    return re.sub(r"[^a-z0-9' ]+", " ", text.lower().replace("-", " ")).split()


def similarity(a: str, b: str) -> float:
    wa, wb = words(a), words(b)
    if not wa or not wb:
        return 0.0
    return difflib.SequenceMatcher(a=wa, b=wb).ratio()


def wer(ref: str, hyp: str) -> float:
    r, h = words(ref), words(hyp)
    if not r:
        return 1.0
    d = list(range(len(h) + 1))
    for i in range(1, len(r) + 1):
        prev, d[0] = d[0], i
        for j in range(1, len(h) + 1):
            cur = d[j]
            d[j] = min(d[j] + 1, d[j - 1] + 1, prev + (r[i - 1] != h[j - 1]))
            prev = cur
    return d[len(h)] / len(r)


def asr(ws: Workspace, gpu: dict, files: list[Path], out_json: Path, model: str) -> dict[str, str]:
    """Whisper transcripts {path: text}; {} if Whisper can't be loaded (e.g. offline)."""
    job = out_json.with_suffix(".job.json")
    write_json(job, {"files": [str(f) for f in files], "model": model})
    rc, tail, _ = side(ws, gpu, "transcribe.py", job, out_json, check=False)
    if rc == 3 or rc != 0:
        LOG.warning("Whisper is unavailable (%s); continuing without it",
                    next((line for line in tail if line.startswith("ASR_UNAVAILABLE")), f"exit {rc}"))
        return {}
    return read_json(out_json, {}) or {}


def reference_stats(ws: Workspace) -> dict:
    from .tune import reference
    return reference(ws)


def timbre(path: Path, ref: dict) -> float:
    x, sr = A.read_wav(path)
    m = EV._active_mfcc(x, sr)
    if len(m) < 20:
        return float("nan")
    return EV.frechet(m.mean(axis=0), np.cov(m, rowvar=False), ref["mu"], ref["cov"])


# ----------------------------------------------------------------------------- build steps

def step_setup(ws: Workspace, a) -> dict:
    py = tts_python(ws)
    if not py.exists():
        LOG.info("Creating the TTS venv (Python 3.12)")
        run([a.uv, "venv", ws.env / "tts", "--python", "3.12"], log_name="setup.log", logs_dir=ws.logs)
    marker = ws.env / "tts" / f".glados_f5_{F5_VERSION}"
    if a.allow_cpu:
        if not marker.exists():
            run([a.uv, "pip", "install", "--python", py, f"torch=={AP.TORCH_VERSION}",
                 f"torchaudio=={AP.TORCH_VERSION}", f"f5-tts=={F5_VERSION}", "soundfile", "soxr"],
                log_name="setup.log", logs_dir=ws.logs)
    else:
        info = AP._torch_info(ws, py)
        idx = ("cu" + info["cuda_build"].replace(".", "")) if info and info.get("cuda_build") else None
        if not (info and info["cuda_build"] and info["cuda_available"]):
            idx = AP._install_torch(ws, a.uv, reinstall=bool(info), python=py)
        if not marker.exists():
            LOG.info("Installing F5-TTS %s", F5_VERSION)
            run([a.uv, "pip", "install", "--python", py, f"f5-tts=={F5_VERSION}", "soundfile", "soxr",
                 "--extra-index-url", f"https://download.pytorch.org/whl/{idx}", "--index-strategy",
                 "unsafe-best-match"], log_name="setup.log", logs_dir=ws.logs)
        info = AP._torch_info(ws, py)
        if not (info and info["cuda_build"] and info["cuda_available"]):
            AP._install_torch(ws, a.uv, reinstall=True, python=py)
    marker.write_text(now())
    info = AP._torch_info(ws, py) or {}
    return {"f5_tts": F5_VERSION, "torch": info.get("version"), "cuda": info.get("cuda_build")}


def step_transcripts(ws: Workspace, a, gpu: dict, state: State) -> dict:
    manifest = {r["id"]: r["rel_path"] for r in csv.DictReader(open(ws.raw / "manifest.csv", encoding="utf-8"))}
    lines = [(p, "train") for p in sorted(ws.dataset.glob("*.wav"))] + \
            [(p, "holdout") for p in sorted(ws.holdout.glob("*.wav"))]
    game = state.info("locate").get("game_dir")
    captions = read_game_captions(Path(game)) if game and Path(game).exists() else {}
    tdir = ws.root / "tts"
    tdir.mkdir(parents=True, exist_ok=True)
    heard = asr(ws, gpu, [p for p, _ in lines], tdir / "whisper.json", a.asr_model)
    rows, counts = [], {"caption, confirmed by Whisper": 0, "Whisper (caption differs)": 0,
                        "Whisper (no caption)": 0, "caption (not checked: no Whisper)": 0, "no text": 0}
    for p, split in lines:
        rel = manifest.get(p.stem, "").lower()
        cap = captions.get(rel, "")
        whi = heard.get(str(p), "")
        sim = similarity(cap, whi) if cap and whi else None
        if cap and whi:
            text, src = (cap, "caption, confirmed by Whisper") if sim >= 0.75 else (whi, "Whisper (caption differs)")
        elif whi:
            text, src = whi, "Whisper (no caption)"
        elif cap:
            text, src = cap, "caption (not checked: no Whisper)"
        else:
            text, src = "", "no text"
        counts[src] += 1
        rows.append({"id": p.stem, "split": split, "text": text, "source": src,
                     "similarity": "" if sim is None else round(sim, 3), "caption": cap, "whisper": whi,
                     "seconds": round(A.read_wav(p)[0].size / A.TARGET_SR, 2)})
    with open(tdir / "transcripts.csv", "w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)
    usable = sum(1 for r in rows if r["text"] and r["split"] == "train")
    min_lines = getattr(a, "min_lines", 20)
    LOG.info("Transcripts for %d lines -> %s: %s", len(rows), tdir / "transcripts.csv",
             ", ".join(f"{v} {k}" for k, v in counts.items() if v))
    if usable < min_lines:
        raise Blocked(f"Only {usable} training lines have a transcript. Whisper needs internet access to "
                      "download its model the first time; check the connection and re-run tts.bat.")
    return {"lines": len(rows), "usable_train": usable, **{k: v for k, v in counts.items() if v}}


def _transcripts(ws: Workspace) -> list[dict]:
    return list(csv.DictReader(open(ws.root / "tts" / "transcripts.csv", encoding="utf-8")))


def step_dataset(ws: Workspace, gpu: dict) -> dict:
    items = [{"audio": str((ws.dataset / f"{r['id']}.wav").resolve()), "text": r["text"]}
             for r in _transcripts(ws) if r["split"] == "train" and r["text"]]
    job = ws.root / "tts" / "dataset_items.json"
    write_json(job, {"items": items})
    rc, tail, _ = side(ws, gpu, "prepare.py", job)
    res = AP.json_line(tail, "PREPARE_JSON ")
    if not res:
        raise StepFailed("Writing the F5-TTS dataset failed:\n" + "\n".join(tail[-15:]))
    LOG.info("F5-TTS fine-tuning set: %d lines, %.1f min (%d skipped: empty or outside 0.3-30 s)",
             res["lines"], res["minutes"], res["skipped"])
    return res


class _Slimmer(threading.Thread):
    """Shrinks each finished intermediate checkpoint to fp16 EMA weights while training runs."""

    def __init__(self, ws: Workspace, gpu: dict, ckpts: Path):
        super().__init__(daemon=True)
        self.ws, self.gpu, self.ckpts, self.stop = ws, gpu, ckpts, threading.Event()
        self.seen: dict[str, tuple] = {}
        self.lock = threading.Lock()

    def sweep(self, final: bool = False):
        with self.lock:
            self._sweep(final)

    def _sweep(self, final: bool):
        for p in sorted(self.ckpts.glob("model_*.pt")):
            if p.name == "model_last.pt" or not re.fullmatch(r"model_\d+\.pt", p.name) or not p.exists():
                continue
            st = p.stat()
            key = (st.st_size, st.st_mtime_ns)
            stable = self.seen.get(p.name) == key and time.time() - st.st_mtime > 30
            self.seen[p.name] = key
            if stable or final:
                run([tts_python(self.ws), SIDE / "slim.py", p, p.with_name("ema_" + p.name[len("model_"):])],
                    cwd=self.ws.root, env=tts_env(self.ws, {"device": "cpu"}), log_name="tts_train.log",
                    logs_dir=self.ws.logs, check=False, quiet=True)

    def run(self):
        while not self.stop.wait(30):
            try:
                self.sweep()
            except Exception as exc:
                LOG.debug("slimmer: %s", exc)


def _drop_broken_checkpoints(ckpts: Path):
    """A save cut short (power loss, full disk) leaves a truncated .pt that F5-TTS would try
    to resume from and crash on. PyTorch checkpoints are zip files: if one won't open, delete it
    so training resumes from the newest intact one."""
    import zipfile

    for p in sorted(ckpts.glob("model_*.pt")) + sorted(ckpts.glob("*.part")):
        try:
            if p.suffix == ".part":
                raise zipfile.BadZipFile("partial")
            zipfile.ZipFile(p).close()
        except (zipfile.BadZipFile, OSError) as exc:
            LOG.warning("Removing damaged checkpoint %s (%s)", p.name, exc)
            p.unlink(missing_ok=True)


def step_train(ws: Workspace, a, gpu: dict, state: State) -> dict:
    prep = state.info("tts_dataset")
    live = state.step("tts_train").setdefault("info", {})
    frames = prep["minutes"] * 60 * 24000 / 256
    batch = int(live.get("batch_frames", a.batch_frames))
    ckpts = Path(prep["ckpts"])
    ckpts.mkdir(parents=True, exist_ok=True)
    free = disk_free_gb(ckpts)
    if free < a.min_free_gb:
        raise Blocked(f"Only {free:.0f} GB free on the drive holding {ckpts}; F5-TTS fine-tuning needs about "
                      f"{a.min_free_gb:g} GB while it runs. Free some space and run tts.bat again.")
    while True:
        per_epoch = max(1, math.ceil(frames / batch))
        epochs = max(1, math.ceil(a.updates / per_epoch))
        save_per = a.save_per or max(1, a.updates // 5)
        args = ["--exp_name", "F5TTS_v1_Base", "--dataset_name", "GLaDOS", "--finetune", "--tokenizer", "pinyin",
                "--learning_rate", "1e-5", "--batch_size_per_gpu", batch, "--batch_size_type", "frame",
                "--max_samples", "64", "--epochs", epochs, "--num_warmup_updates", max(1, min(1000, a.updates // 10)),
                "--save_per_updates", save_per, "--last_per_updates", max(1, min(500, a.updates // 20)),
                "--keep_last_n_checkpoints", "6"]
        if a.f5_pretrain:
            args += ["--pretrain", a.f5_pretrain]
        if gpu.get("device") == "cuda" and not live.get("no_bnb"):
            args += ["--bnb_optimizer"]
        LOG.info("Fine-tuning F5-TTS: about %d updates (%d epochs of ~%d), %d frames per batch; checkpoints in %s",
                 a.updates, epochs, per_epoch, batch, ckpts)
        mon = {"oom": False, "ram": False, "done": False}

        def on_line(line):
            if any(m in line for m in AP.OOM_MARKERS):
                mon["oom"] = True
                return "kill"
            if "MemoryError" in line or "can't allocate memory" in line or "not enough memory" in line:
                mon["ram"] = True
                return "kill"
            if "FINETUNE_DONE" in line:
                mon["done"] = True
            return None

        _drop_broken_checkpoints(ckpts)
        slimmer = _Slimmer(ws, gpu, ckpts)
        slimmer.start()
        workers = int(live.get("workers", 4))
        rc, tail, _ = side(ws, gpu, "finetune.py", *args, log_name="tts_train.log", on_line=on_line, check=False,
                           workers=workers)
        slimmer.stop.set()
        slimmer.join(timeout=600)
        slimmer.sweep(final=True)
        if rc in (-9, 137) and not mon["done"]:
            mon["ram"] = True  # killed by the system: nearly always out of RAM
        if mon["ram"]:
            if workers <= 1 and batch <= 400:
                raise Blocked("F5-TTS fine-tuning runs out of system memory (RAM) even with minimal settings. "
                              "Close other programs and run tts.bat again.")
            live["workers"] = 1
            batch = max(400, int(batch * 0.7))
            live["batch_frames"] = batch
            state.save()
            LOG.warning("Out of system memory; retrying with one data-loader worker and %d frames per batch", batch)
            continue
        if mon["oom"]:
            if batch <= 400:
                raise Blocked("F5-TTS runs out of GPU memory even at small batches. Close other programs "
                              "using the GPU and run tts.bat again.")
            batch = int(batch * 0.7)
            live["batch_frames"] = batch
            state.save()
            LOG.warning("Out of GPU memory; resuming with %d frames per batch", batch)
            continue
        if rc == 0 and mon["done"]:
            break
        if not live.get("no_bnb") and any("bitsandbytes" in line.lower() for line in tail):
            # 8-bit Adam could not load (a DLL/CUDA mismatch on some Windows setups): use
            # standard AdamW, which needs more memory, so start from a smaller batch.
            live["no_bnb"] = True
            batch = int(batch * 0.75)
            live["batch_frames"] = batch
            state.save()
            LOG.warning("8-bit Adam (bitsandbytes) failed to load; continuing with standard AdamW and "
                        "%d frames per batch", batch)
            continue
        live["restarts"] = live.get("restarts", 0) + 1
        state.save()
        if live["restarts"] > 3:
            raise StepFailed("F5-TTS fine-tuning keeps failing:\n" + "\n".join(tail[-30:]))
        LOG.warning("Fine-tuning stopped (exit %s); resuming from its last checkpoint", rc)
    saved = sorted(p.name for p in list(ckpts.glob("ema_*.pt")) + list(ckpts.glob("model_*.pt")))
    return {"updates": a.updates, "batch_frames": batch, "checkpoints": saved, "ckpt_dir": str(ckpts)}


def _pick_reference(rows: list[dict]) -> dict:
    good = [r for r in rows if r["split"] == "train" and r["text"] and 4.0 <= float(r["seconds"]) <= 9.0]
    good.sort(key=lambda r: (not r["source"].startswith("caption, confirmed"), abs(float(r["seconds"]) - 7.0)))
    if not good:
        good = sorted((r for r in rows if r["split"] == "train" and r["text"]), key=lambda r: -float(r["seconds"]))
    if not good:
        raise StepFailed("No transcribed line is usable as the TTS voice reference")
    return good[0]


def step_select(ws: Workspace, a, gpu: dict, state: State) -> dict:
    tr = state.info("tts_train")
    ckdir = Path(tr["ckpt_dir"])
    def update_no(p: Path) -> int:
        m = re.search(r"(\d+)", p.stem)
        return int(m.group(1)) if m else 0

    snaps = sorted(list(ckdir.glob("ema_*.pt")) + [p for p in ckdir.glob("model_*.pt") if p.name != "model_last.pt"],
                   key=update_no)
    last = [ckdir / "model_last.pt"] if (ckdir / "model_last.pt").exists() else []
    base = sorted(ckdir.glob("pretrained_*"))
    cands = base[:1] + snaps + last
    rows = _transcripts(ws)
    ref = _pick_reference(rows)
    ref_wav = ws.root / "tts" / "reference.wav"
    x, sr = A.read_wav(ws.dataset / f"{ref['id']}.wav")
    A.write_wav16(ref_wav, A.resample(x, sr, 24000), 24000)
    tests = [r for r in rows if r["split"] == "holdout" and r["text"]][:6]
    if not tests:
        tests = [r for r in rows if r["split"] == "train" and r["text"] and r["id"] != ref["id"]][:6]
    vocab = str(Path(state.info("tts_dataset")["vocab"]))
    sel_dir = ws.root / "tts" / "select"
    results = []
    refstats = reference_stats(ws)
    for ck in cands:
        outs = [sel_dir / ck.stem / f"{t['id']}.wav" for t in tests]
        job = {"ckpt": str(ck), "vocab": vocab, "vocoder_local": a.vocoder_local, "ref_audio": str(ref_wav),
               "ref_text": ref["text"], "nfe_step": a.nfe_step,
               "items": [{"text": t["text"], "out": str(o), "seed": 1234} for t, o in zip(tests, outs)]}
        write_json(sel_dir / f"{ck.stem}.job.json", job)
        side(ws, gpu, "generate.py", sel_dir / f"{ck.stem}.job.json", log_name="tts_select.log")
        results.append({"ckpt": ck, "outs": outs})
    heard = asr(ws, gpu, [o for r in results for o in r["outs"]], sel_dir / "whisper.json", a.asr_model)
    for r in results:
        r["wer"] = float(np.mean([wer(t["text"], heard[str(o)]) for t, o in zip(tests, r["outs"])])) if heard else float("nan")
        r["timbre"] = float(np.nanmean([timbre(o, refstats) for o in r["outs"]]))
    med = float(np.nanmedian([r["timbre"] for r in results])) or 1.0
    for r in results:
        r["score"] = (2.0 * r["wer"] if np.isfinite(r["wer"]) else 0.0) + r["timbre"] / med
    best = min(results, key=lambda r: r["score"])
    table = [{"checkpoint": r["ckpt"].name, "word_error_rate": None if not np.isfinite(r["wer"]) else round(r["wer"], 3),
              "timbre_distance": round(r["timbre"], 3), "score": round(r["score"], 3)} for r in results]
    write_json(ws.root / "tts" / "selection.json", {"chosen": best["ckpt"].name, "table": table,
                                                    "reference": ref, "tests": [t["id"] for t in tests]})
    for row in table:
        LOG.info("   %-40s WER %-6s timbre %-8s score %.3f%s", row["checkpoint"], row["word_error_rate"],
                 row["timbre_distance"], row["score"], "  <- chosen" if row["checkpoint"] == best["ckpt"].name else "")
    if not heard:
        LOG.warning("Chosen on timbre only (no Whisper, so pronunciation errors were not measured)")
    return {"ckpt": str(best["ckpt"]), "chosen": best["ckpt"].name, "vocab": vocab, "ref_audio": str(ref_wav),
            "ref_text": ref["text"], "used_whisper": bool(heard)}


# ----------------------------------------------------------------------------- speaking

def slug(text: str, n: int = 40) -> str:
    return (re.sub(r"[^A-Za-z0-9]+", "_", text).strip("_")[:n] or "line").lower()


def speak(ws: Workspace, a, gpu: dict, state: State, texts: list[str]) -> Path:
    sel = state.info("tts_select")
    stamp = _dt.datetime.now().strftime("%Y%m%d_%H%M%S")
    out = ws.root / "tts" / "out" / f"{stamp}_{slug(texts[0])}"
    items = []
    for li, text in enumerate(texts, 1):
        for k in range(1, a.takes + 1):
            items.append({"text": text, "out": str(out / "raw" / f"line{li:02d}_take{k}.wav"),
                          "seed": 1000 * li + k, "line": li, "take": k})
    job = {"ckpt": sel["ckpt"], "vocab": sel["vocab"], "vocoder_local": a.vocoder_local,
           "ref_audio": sel["ref_audio"], "ref_text": sel["ref_text"], "nfe_step": a.nfe_step, "items": items}
    write_json(out / "generate.job.json", job)
    LOG.info("Generating %d take(s) of %d line(s) with %s", a.takes, len(texts), Path(sel["ckpt"]).name)
    side(ws, gpu, "generate.py", out / "generate.job.json", log_name="tts_speak.log")

    pth, idx = V.model_files(ws)
    s = V.Settings(pitch=0, index_rate=a.index_rate, protect=0.33, autotune_strength=a.steps)
    pairs = [(Path(it["out"]), out / "rvc" / Path(it["out"]).name) for it in items]
    for _, o in pairs:
        o.unlink(missing_ok=True)
    V.run_jobs(ws, [V.job(pth, idx, s, pairs)], out / "rvc.job.json", "tts_speak.log")

    heard = asr(ws, gpu, [o for _, o in pairs], out / "whisper.json", a.asr_model) if not a.no_rank_asr else {}
    refstats = reference_stats(ws)
    rows = []
    for it, (_, o) in zip(items, pairs):
        w = wer(it["text"], heard[str(o)]) if heard else float("nan")
        rows.append({"line": it["line"], "take": it["take"], "text": it["text"], "file": o,
                     "word_error_rate": w, "heard": heard.get(str(o), ""), "timbre": timbre(o, refstats)})
    with open(out / "ranking.csv", "w", newline="", encoding="utf-8") as fh:
        wtr = csv.writer(fh)
        wtr.writerow(["line", "rank", "take", "word_error_rate", "timbre_distance", "file", "text", "whisper_heard"])
        for li in range(1, len(texts) + 1):
            takes = sorted((r for r in rows if r["line"] == li),
                           key=lambda r: ((r["word_error_rate"] if np.isfinite(r["word_error_rate"]) else 0), r["timbre"]))
            for rank, r in enumerate(takes, 1):
                wtr.writerow([li, rank, r["take"], "" if not np.isfinite(r["word_error_rate"]) else round(r["word_error_rate"], 3),
                              round(r["timbre"], 3), r["file"].name, r["text"], r["heard"]])
            shutil.copyfile(takes[0]["file"], out / f"line{li:02d}_best.wav")
            V.concat_with_gaps([r["file"] for r in takes], out / f"line{li:02d}_all_takes.wav")
            LOG.info("Line %d: best is take %d%s -> %s", li, takes[0]["take"],
                     f" (Whisper heard: \"{takes[0]['heard']}\")" if takes[0]["heard"] else "", out / f"line{li:02d}_best.wav")
    LOG.info("All takes (ranked) in %s; ranking.csv explains the order", out)
    return out


# ----------------------------------------------------------------------------- CLI

def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(prog="tts.bat", description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("text", nargs="*", help="line(s) to speak; none = just build the model")
    ap.add_argument("--file", help="text file, one line per row")
    ap.add_argument("--takes", type=int, default=5)
    ap.add_argument("--steps", type=float, default=0.0, help="GLaDOS-mode step strength on the RVC pass (0-1)")
    ap.add_argument("--index-rate", type=float, default=0.5, help="RVC index rate for the polish pass")
    ap.add_argument("--nfe-step", type=int, default=32, help="F5-TTS sampling steps (quality vs speed)")
    ap.add_argument("--updates", type=int, default=20000, help="fine-tuning length in optimiser updates")
    ap.add_argument("--batch-frames", type=int, default=1536, help="starting batch size in mel frames (8 GB default)")
    ap.add_argument("--redo", choices=[s for s, _ in STEPS], help="redo this build step and the ones after it")
    ap.add_argument("--root", default=r"C:\GLaDOSVoice")
    ap.add_argument("--uv", help=argparse.SUPPRESS)
    ap.add_argument("--asr-model", default=ASR_MODEL, help=argparse.SUPPRESS)
    ap.add_argument("--f5-pretrain", help=argparse.SUPPRESS)      # local base checkpoint (offline/testing)
    ap.add_argument("--vocoder-local", help=argparse.SUPPRESS)    # local Vocos folder (offline/testing)
    ap.add_argument("--no-rank-asr", action="store_true", help=argparse.SUPPRESS)
    ap.add_argument("--allow-cpu", action="store_true", help=argparse.SUPPRESS)
    ap.add_argument("--min-lines", type=int, default=20, help=argparse.SUPPRESS)
    ap.add_argument("--save-per", type=int, help=argparse.SUPPRESS)
    ap.add_argument("--min-free-gb", type=float, default=15.0, help=argparse.SUPPRESS)
    a = ap.parse_args(argv)

    ws = Workspace(Path(a.root))
    setup_logging(ws)
    state = State(ws.state_file)
    if not state.is_done("export"):
        raise Blocked("Build the voice model first: run run.bat until it finishes, then tts.bat.")
    gpu = V.gpu_for_tools(ws)
    if a.allow_cpu:
        gpu = {"device": "cpu"}
    if not a.uv:
        cands = [ws.tools / "uv" / ("uv.exe" if os.name == "nt" else "uv"), shutil.which("uv")]
        a.uv = next((str(c) for c in cands if c and Path(c).exists()), None)
        if not a.uv:
            raise Blocked("uv was not found; start tts.bat (it goes through run.ps1, which installs uv).")
    if a.redo:
        first = [s for s, _ in STEPS].index(a.redo)
        for name, _ in STEPS[first:]:
            state.reset(name)

    runners = {"tts_setup": lambda: step_setup(ws, a),
               "tts_transcripts": lambda: step_transcripts(ws, a, gpu, state),
               "tts_dataset": lambda: step_dataset(ws, gpu),
               "tts_train": lambda: step_train(ws, a, gpu, state),
               "tts_select": lambda: step_select(ws, a, gpu, state)}
    for i, (name, title) in enumerate(STEPS, 1):
        if state.is_done(name):
            continue
        LOG.info("[TTS %d/%d] %s", i, len(STEPS), title)
        state.mark(name, "running")
        t0 = time.time()
        try:
            info = runners[name]()
        except (Blocked, StepFailed):
            state.mark(name, "failed")
            raise
        state.mark(name, "done", {**info, "seconds": round(time.time() - t0)})
        LOG.info("[TTS %d/%d] done in %s", i, len(STEPS), fmt_duration(time.time() - t0))

    texts = list(a.text)
    if a.file:
        texts += [t.strip() for t in Path(a.file).read_text(encoding="utf-8").splitlines() if t.strip()]
    if not texts:
        LOG.info("TTS model ready (%s). Try: tts.bat \"Hello. It's been a long time.\"",
                 state.info("tts_select").get("chosen"))
        return 0
    speak(ws, a, gpu, state, texts)
    return 0
