/**
 * Which of vanilla's sound events each of the game's voices is. The synthesized voices are still
 * there and still carry the same names: they are what plays when the ogg files were never fetched,
 * or for the handful of events Mojang's own table has no file for.
 */
export const SOUND_EVENTS: Record<string, string> = {
  // the blocks under the pick and under the feet
  dig_stone: 'block.stone.break',
  dig_wood: 'block.wood.break',
  dig_gravel: 'block.gravel.break',
  dig_sand: 'block.sand.break',
  dig_grass: 'block.grass.break',
  dig_wool: 'block.wool.break',
  dig_glass: 'block.glass.break',
  dig_water: 'item.bucket.empty',
  dig_snow: 'block.snow.break',
  step_stone: 'block.stone.step',
  step_wood: 'block.wood.step',
  step_gravel: 'block.gravel.step',
  step_sand: 'block.sand.step',
  step_grass: 'block.grass.step',
  step_wool: 'block.wool.step',
  step_glass: 'block.glass.step',
  step_snow: 'block.snow.step',
  step_water: 'block.water.ambient',
  step: 'block.stone.step',
  place: 'block.grass.place',
  break: 'entity.item.break',
  // the player
  hurt: 'entity.player.hurt',
  death: 'entity.player.death',
  eat: 'entity.generic.eat',
  burp: 'entity.player.burp',
  levelup: 'entity.player.levelup',
  level_up: 'entity.player.levelup',
  orb: 'entity.experience_orb.pickup',
  pop: 'entity.item.pickup',
  splash: 'entity.generic.splash',
  // things that go off
  explosion: 'entity.generic.explode',
  explode: 'entity.generic.explode',
  bow: 'entity.arrow.shoot',
  arrow_hit: 'entity.arrow.hit',
  fuse: 'entity.tnt.primed',
  firework: 'entity.firework_rocket.launch',
  creeper_hiss: 'entity.creeper.primed',
  // blocks you use
  door: 'block.wooden_door.open',
  chest: 'block.chest.open',
  note: 'block.note_block.harp',
  click: 'ui.button.click',
  fizz: 'block.fire.extinguish',
  lava_pop: 'block.lava.pop',
  anvil: 'block.anvil.use',
  enchant: 'block.enchantment_table.use',
  stonecutter: 'ui.stonecutter.take_result',
  stonecutter_select: 'ui.stonecutter.select_recipe',
  smithing: 'block.smithing_table.use',
  bottle_fill: 'item.bottle.fill',
  shear: 'entity.sheep.shear',
  saddle: 'entity.horse.saddle',
  shrieker: 'block.sculk_shrieker.shriek',
  // the animals
  cow: 'entity.cow.ambient',
  pig: 'entity.pig.ambient',
  sheep: 'entity.sheep.ambient',
  chicken: 'entity.chicken.ambient',
  cat: 'entity.cat.ambient',
  wolf: 'entity.wolf.ambient',
  wolf_growl: 'entity.wolf.growl',
  horse: 'entity.horse.ambient',
  horse_ambient: 'entity.horse.ambient',
  horse_angry: 'entity.horse.angry',
  horse_eat: 'entity.horse.eat',
  horse_jump: 'entity.horse.jump',
  horse_gallop: 'entity.horse.gallop',
  donkey: 'entity.donkey.ambient',
  bee: 'entity.bee.loop',
  bee_angry: 'entity.bee.loop_aggressive',
  bee_sting: 'entity.bee.sting',
  villager: 'entity.villager.ambient',
  villager_trade: 'entity.villager.trade',
  // the monsters
  zombie: 'entity.zombie.ambient',
  skeleton: 'entity.skeleton.ambient',
  spider: 'entity.spider.ambient',
  slime: 'entity.slime.squish',
  enderman: 'entity.enderman.ambient',
  enderman_teleport: 'entity.enderman.teleport',
  enderman_scream: 'entity.enderman.scream',
  witch: 'entity.witch.ambient',
  phantom: 'entity.phantom.ambient',
  illager: 'entity.pillager.ambient',
  evoker_prepare: 'entity.evoker.prepare_summon',
  evoker_cast: 'entity.evoker.cast_spell',
  evoker_fangs: 'entity.evoker_fangs.attack',
  vex: 'entity.vex.ambient',
  ravager: 'entity.ravager.ambient',
  guardian: 'entity.guardian.ambient',
  guardian_attack: 'entity.guardian.attack',
  guardian_hurt: 'entity.guardian.hurt',
  elder_guardian_curse: 'entity.elder_guardian.curse',
  shulker: 'entity.shulker.ambient',
  shulker_shoot: 'entity.shulker.shoot',
  warden: 'entity.warden.ambient',
  warden_boom: 'entity.warden.sonic_boom',
  warden_boom_charge: 'entity.warden.sonic_charge',
  // the Nether and the bosses
  blaze: 'entity.blaze.ambient',
  blaze_shoot: 'entity.blaze.shoot',
  ghast: 'entity.ghast.ambient',
  ghast_warn: 'entity.ghast.warn',
  ghast_shoot: 'entity.ghast.shoot',
  piglin: 'entity.piglin.ambient',
  hoglin: 'entity.hoglin.ambient',
  strider: 'entity.strider.ambient',
  magma_cube: 'entity.magma_cube.squish',
  wither: 'entity.wither.ambient',
  wither_spawn: 'entity.wither.spawn',
  wither_shoot: 'entity.wither.shoot',
};
