// ===== mini3d — a tiny WebGL2 scene renderer with a Three.js-flavoured API (no dependencies) =====
const THREE=(function(){
class Vector3{ constructor(x=0,y=0,z=0){this.x=x;this.y=y;this.z=z;}
  set(x,y,z){this.x=x;this.y=y;this.z=z;return this;} setY(y){this.y=y;return this;} copy(v){this.x=v.x;this.y=v.y;this.z=v.z;return this;} clone(){return new Vector3(this.x,this.y,this.z);}
  add(v){this.x+=v.x;this.y+=v.y;this.z+=v.z;return this;} sub(v){this.x-=v.x;this.y-=v.y;this.z-=v.z;return this;} addScaledVector(v,s){this.x+=v.x*s;this.y+=v.y*s;this.z+=v.z*s;return this;}
  multiplyScalar(s){this.x*=s;this.y*=s;this.z*=s;return this;} negate(){return this.multiplyScalar(-1);} length(){return Math.hypot(this.x,this.y,this.z);} normalize(){const l=this.length()||1;return this.multiplyScalar(1/l);}
  dot(v){return this.x*v.x+this.y*v.y+this.z*v.z;} crossVectors(a,b){this.x=a.y*b.z-a.z*b.y;this.y=a.z*b.x-a.x*b.z;this.z=a.x*b.y-a.y*b.x;return this;} cross(v){return this.crossVectors(this.clone(),v);}
  lerp(v,t){this.x+=(v.x-this.x)*t;this.y+=(v.y-this.y)*t;this.z+=(v.z-this.z)*t;return this;} setScalar(s){this.x=this.y=this.z=s;return this;}
  applyQuaternion(q){const {x,y,z}=this;const qx=q.x,qy=q.y,qz=q.z,qw=q.w;const ix=qw*x+qy*z-qz*y,iy=qw*y+qz*x-qx*z,iz=qw*z+qx*y-qy*x,iw=-qx*x-qy*y-qz*z;this.x=ix*qw+iw*-qx+iy*-qz-iz*-qy;this.y=iy*qw+iw*-qy+iz*-qx-ix*-qz;this.z=iz*qw+iw*-qz+ix*-qy-iy*-qx;return this;}
  applyMatrix4(m){const e=m.e,{x,y,z}=this;const w=1/((e[3]*x+e[7]*y+e[11]*z+e[15])||1);this.x=(e[0]*x+e[4]*y+e[8]*z+e[12])*w;this.y=(e[1]*x+e[5]*y+e[9]*z+e[13])*w;this.z=(e[2]*x+e[6]*y+e[10]*z+e[14])*w;return this;}
  distanceTo(v){return Math.hypot(this.x-v.x,this.y-v.y,this.z-v.z);} }
class Quaternion{ constructor(x=0,y=0,z=0,w=1){this.x=x;this.y=y;this.z=z;this.w=w;}
  set(x,y,z,w){this.x=x;this.y=y;this.z=z;this.w=w;return this;} copy(q){return this.set(q.x,q.y,q.z,q.w);} clone(){return new Quaternion(this.x,this.y,this.z,this.w);} identity(){return this.set(0,0,0,1);}
  setFromAxisAngle(a,ang){const h=ang/2,s=Math.sin(h);this.x=a.x*s;this.y=a.y*s;this.z=a.z*s;this.w=Math.cos(h);return this;}
  setFromEuler(e){const c1=Math.cos(e.x/2),c2=Math.cos(e.y/2),c3=Math.cos(e.z/2),s1=Math.sin(e.x/2),s2=Math.sin(e.y/2),s3=Math.sin(e.z/2);this.x=s1*c2*c3+c1*s2*s3;this.y=c1*s2*c3-s1*c2*s3;this.z=c1*c2*s3+s1*s2*c3;this.w=c1*c2*c3-s1*s2*s3;return this;}
  multiply(q){return this.multiplyQuaternions(this,q);} premultiply(q){return this.multiplyQuaternions(q,this);}
  multiplyQuaternions(a,b){const ax=a.x,ay=a.y,az=a.z,aw=a.w,bx=b.x,by=b.y,bz=b.z,bw=b.w;this.x=ax*bw+aw*bx+ay*bz-az*by;this.y=ay*bw+aw*by+az*bx-ax*bz;this.z=az*bw+aw*bz+ax*by-ay*bx;this.w=aw*bw-ax*bx-ay*by-az*bz;return this;}
  slerp(q,t){if(t<=0)return this;if(t>=1)return this.copy(q);let cos=this.x*q.x+this.y*q.y+this.z*q.z+this.w*q.w;let qx=q.x,qy=q.y,qz=q.z,qw=q.w;if(cos<0){cos=-cos;qx=-qx;qy=-qy;qz=-qz;qw=-qw;}if(cos>0.9995){this.x+=(qx-this.x)*t;this.y+=(qy-this.y)*t;this.z+=(qz-this.z)*t;this.w+=(qw-this.w)*t;return this.normalize();}const th=Math.acos(cos),s=Math.sin(th),a=Math.sin((1-t)*th)/s,b=Math.sin(t*th)/s;this.x=this.x*a+qx*b;this.y=this.y*a+qy*b;this.z=this.z*a+qz*b;this.w=this.w*a+qw*b;return this;}
  normalize(){const l=Math.hypot(this.x,this.y,this.z,this.w)||1;this.x/=l;this.y/=l;this.z/=l;this.w/=l;return this;} }
class Euler{ constructor(x=0,y=0,z=0){this.x=x;this.y=y;this.z=z;} set(x,y,z){this.x=x;this.y=y;this.z=z;return this;} }
class Matrix4{ constructor(){this.e=new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);}
  identity(){this.e.set([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);return this;} copy(m){this.e.set(m.e);return this;} clone(){return new Matrix4().copy(this);}
  compose(p,q,s){const e=this.e,x=q.x,y=q.y,z=q.z,w=q.w,x2=x+x,y2=y+y,z2=z+z,xx=x*x2,xy=x*y2,xz=x*z2,yy=y*y2,yz=y*z2,zz=z*z2,wx=w*x2,wy=w*y2,wz=w*z2,sx=s.x,sy=s.y,sz=s.z;
    e[0]=(1-(yy+zz))*sx;e[1]=(xy+wz)*sx;e[2]=(xz-wy)*sx;e[3]=0;e[4]=(xy-wz)*sy;e[5]=(1-(xx+zz))*sy;e[6]=(yz+wx)*sy;e[7]=0;e[8]=(xz+wy)*sz;e[9]=(yz-wx)*sz;e[10]=(1-(xx+yy))*sz;e[11]=0;e[12]=p.x;e[13]=p.y;e[14]=p.z;e[15]=1;return this;}
  multiplyMatrices(a,b){const ae=a.e,be=b.e,te=new Float32Array(16);for(let i=0;i<4;i++)for(let j=0;j<4;j++){te[j*4+i]=ae[i]*be[j*4]+ae[4+i]*be[j*4+1]+ae[8+i]*be[j*4+2]+ae[12+i]*be[j*4+3];}this.e=te;return this;}
  multiply(m){return this.multiplyMatrices(this,m);}
  perspective(fov,aspect,near,far){const f=1/Math.tan(fov/2),e=this.e;e.fill(0);e[0]=f/aspect;e[5]=f;e[10]=(far+near)/(near-far);e[11]=-1;e[14]=2*far*near/(near-far);return this;}
  ortho(l,r,b,t,n,f){const e=this.e;e.fill(0);e[0]=2/(r-l);e[5]=2/(t-b);e[10]=-2/(f-n);e[12]=-(r+l)/(r-l);e[13]=-(t+b)/(t-b);e[14]=-(f+n)/(f-n);e[15]=1;return this;}
  lookAt(eye,target,up){const z=eye.clone().sub(target).normalize();if(z.length()===0)z.z=1;const x=new Vector3().crossVectors(up,z).normalize();if(x.length()===0){z.x+=1e-4;x.crossVectors(up,z).normalize();}const y=new Vector3().crossVectors(z,x);const e=this.e;e[0]=x.x;e[1]=y.x;e[2]=z.x;e[3]=0;e[4]=x.y;e[5]=y.y;e[6]=z.y;e[7]=0;e[8]=x.z;e[9]=y.z;e[10]=z.z;e[11]=0;e[12]=-x.dot(eye);e[13]=-y.dot(eye);e[14]=-z.dot(eye);e[15]=1;return this;}
  invert(){const e=this.e,n11=e[0],n21=e[1],n31=e[2],n41=e[3],n12=e[4],n22=e[5],n32=e[6],n42=e[7],n13=e[8],n23=e[9],n33=e[10],n43=e[11],n14=e[12],n24=e[13],n34=e[14],n44=e[15],t11=n23*n34*n42-n24*n33*n42+n24*n32*n43-n22*n34*n43-n23*n32*n44+n22*n33*n44,t12=n14*n33*n42-n13*n34*n42-n14*n32*n43+n12*n34*n43+n13*n32*n44-n12*n33*n44,t13=n13*n24*n42-n14*n23*n42+n14*n22*n43-n12*n24*n43-n13*n22*n44+n12*n23*n44,t14=n14*n23*n32-n13*n24*n32-n14*n22*n33+n12*n24*n33+n13*n22*n34-n12*n23*n34;const det=n11*t11+n21*t12+n31*t13+n41*t14;if(det===0)return this.identity();const d=1/det;e[0]=t11*d;e[1]=(n24*n33*n41-n23*n34*n41-n24*n31*n43+n21*n34*n43+n23*n31*n44-n21*n33*n44)*d;e[2]=(n22*n34*n41-n24*n32*n41+n24*n31*n42-n21*n34*n42-n22*n31*n44+n21*n32*n44)*d;e[3]=(n23*n32*n41-n22*n33*n41-n23*n31*n42+n21*n33*n42+n22*n31*n43-n21*n32*n43)*d;e[4]=t12*d;e[5]=(n13*n34*n41-n14*n33*n41+n14*n31*n43-n11*n34*n43-n13*n31*n44+n11*n33*n44)*d;e[6]=(n14*n32*n41-n12*n34*n41-n14*n31*n42+n11*n34*n42+n12*n31*n44-n11*n32*n44)*d;e[7]=(n12*n33*n41-n13*n32*n41+n13*n31*n42-n11*n33*n42-n12*n31*n43+n11*n32*n43)*d;e[8]=t13*d;e[9]=(n14*n23*n41-n13*n24*n41-n14*n21*n43+n11*n24*n43+n13*n21*n44-n11*n23*n44)*d;e[10]=(n12*n24*n41-n14*n22*n41+n14*n21*n42-n11*n24*n42-n12*n21*n44+n11*n22*n44)*d;e[11]=(n13*n22*n41-n12*n23*n41-n13*n21*n42+n11*n23*n42+n12*n21*n43-n11*n22*n43)*d;e[12]=t14*d;e[13]=(n13*n24*n31-n14*n23*n31+n14*n21*n33-n11*n24*n33-n13*n21*n34+n11*n23*n34)*d;e[14]=(n14*n22*n31-n12*n24*n31-n14*n21*n32+n11*n24*n32+n12*n21*n34-n11*n22*n34)*d;e[15]=(n12*n23*n31-n13*n22*n31+n13*n21*n32-n11*n23*n32-n12*n21*n33+n11*n22*n33)*d;return this;} }
class Color{ constructor(c){this.set(c);} set(c){ if(c instanceof Color){this.r=c.r;this.g=c.g;this.b=c.b;} else if(typeof c==='number'){this.r=((c>>16)&255)/255;this.g=((c>>8)&255)/255;this.b=(c&255)/255;} else {this.r=this.g=this.b=1;} return this;} clone(){return new Color(this);} }
// ---- geometry ----
class BufferGeometry{ constructor(pos,nrm,idx,lines){ this.pos=new Float32Array(pos); this.nrm=nrm?new Float32Array(nrm):null; this.idx=idx?new Uint16Array(idx):null; this.lines=!!lines; this._gl=null; } }
function buildBox(hx,hy,hz){ const P=[],N=[],I=[]; const F=[[1,0,0],[-1,0,0],[0,1,0],[0,-1,0],[0,0,1],[0,0,-1]];
  F.forEach(n=>{ const b=P.length/3; const a=Math.abs(n[1])>0.5?[1,0,0]:[0,1,0]; const u=[n[1]*a[2]-n[2]*a[1],n[2]*a[0]-n[0]*a[2],n[0]*a[1]-n[1]*a[0]]; const v=[n[1]*u[2]-n[2]*u[1],n[2]*u[0]-n[0]*u[2],n[0]*u[1]-n[1]*u[0]];
    for(const [su,sv] of [[-1,-1],[1,-1],[1,1],[-1,1]]){ const x=n[0]+u[0]*su+v[0]*sv, y=n[1]+u[1]*su+v[1]*sv, z=n[2]+u[2]*su+v[2]*sv; P.push(x*hx,y*hy,z*hz); N.push(...n);} I.push(b,b+1,b+2,b,b+2,b+3); });
  const g=new BufferGeometry(P,N,I); g.box=[hx,hy,hz]; return g; }
function EdgesGeometry_(g){ const [hx,hy,hz]=g.box||[.5,.5,.5]; const c=[]; for(const sx of [-1,1])for(const sy of [-1,1])for(const sz of [-1,1]) c.push([sx*hx,sy*hy,sz*hz]); const P=[]; for(let i=0;i<8;i++)for(let j=i+1;j<8;j++){ let diff=0; for(let k=0;k<3;k++) if(c[i][k]!==c[j][k]) diff++; if(diff===1){ P.push(...c[i],...c[j]); } } return new BufferGeometry(P,null,null,true); }
function CylinderGeometry_(rt=1,rb=1,h=1,seg=16){ const P=[],N=[],I=[]; for(let i=0;i<=seg;i++){ const a=i/seg*Math.PI*2,c=Math.cos(a),s=Math.sin(a); P.push(c*rt,h/2,s*rt); N.push(c,0,s); P.push(c*rb,-h/2,s*rb); N.push(c,0,s);} for(let i=0;i<seg;i++){ const b=i*2; I.push(b,b+2,b+1,b+1,b+2,b+3);} const bt=P.length/3; P.push(0,h/2,0); N.push(0,1,0); for(let i=0;i<=seg;i++){ const a=i/seg*Math.PI*2; P.push(Math.cos(a)*rt,h/2,Math.sin(a)*rt); N.push(0,1,0);} for(let i=0;i<seg;i++) I.push(bt,bt+1+i+1,bt+1+i); const bb=P.length/3; P.push(0,-h/2,0); N.push(0,-1,0); for(let i=0;i<=seg;i++){ const a=i/seg*Math.PI*2; P.push(Math.cos(a)*rb,-h/2,Math.sin(a)*rb); N.push(0,-1,0);} for(let i=0;i<seg;i++) I.push(bb,bb+1+i,bb+1+i+1); return new BufferGeometry(P,N,I); }
function TorusGeometry_(R=1,r=.3,ts=8,rs=24){ const P=[],N=[],I=[]; for(let j=0;j<=ts;j++)for(let i=0;i<=rs;i++){ const u=i/rs*Math.PI*2,v=j/ts*Math.PI*2; const cx=Math.cos(u)*(R+r*Math.cos(v)),cy=Math.sin(u)*(R+r*Math.cos(v)),cz=r*Math.sin(v); P.push(cx,cy,cz); const nx=Math.cos(u)*Math.cos(v),ny=Math.sin(u)*Math.cos(v),nz=Math.sin(v); N.push(nx,ny,nz);} for(let j=1;j<=ts;j++)for(let i=1;i<=rs;i++){ const a=(rs+1)*j+i-1,b=(rs+1)*(j-1)+i-1,c=(rs+1)*(j-1)+i,d=(rs+1)*j+i; I.push(a,b,d,b,c,d);} return new BufferGeometry(P,N,I); }
function OctahedronGeometry_(r=1){ const V=[[1,0,0],[-1,0,0],[0,1,0],[0,-1,0],[0,0,1],[0,0,-1]]; const F=[[0,2,4],[0,5,2],[1,4,2],[1,2,5],[0,4,3],[0,3,5],[1,3,4],[1,5,3]]; const P=[],N=[],I=[]; F.forEach(f=>{ const a=V[f[0]],b=V[f[1]],c=V[f[2]]; const n=[(a[0]+b[0]+c[0]),(a[1]+b[1]+c[1]),(a[2]+b[2]+c[2])]; const l=Math.hypot(...n); const bi=P.length/3; [a,b,c].forEach(p=>{ P.push(p[0]*r,p[1]*r,p[2]*r); N.push(n[0]/l,n[1]/l,n[2]/l);}); I.push(bi,bi+1,bi+2); }); return new BufferGeometry(P,N,I); }
function PlaneGeometry_(w=1,h=1){ const hx=w/2,hy=h/2; return new BufferGeometry([-hx,-hy,0,hx,-hy,0,hx,hy,0,-hx,hy,0],[0,0,1,0,0,1,0,0,1,0,0,1],[0,1,2,0,2,3]); }
// ---- materials ----
class Material{ constructor(o={}){ this.color=new Color(o.color??0xffffff); this.sideColor=o.sideColor!==undefined?new Color(o.sideColor):null; this.emissive=new Color(o.emissive??0x000000); this.emissiveIntensity=o.emissiveIntensity??1; this.roughness=o.roughness??.6; this.metalness=o.metalness??0; this.opacity=o.opacity??1; this.transparent=!!o.transparent; this.depthWrite=o.depthWrite??true; this.unlit=false; } clone(){ const m=new this.constructor({}); Object.assign(m,this); m.color=this.color.clone(); m.emissive=this.emissive.clone(); m.sideColor=this.sideColor?this.sideColor.clone():null; return m; } }
class MeshStandardMaterial extends Material{}
class MeshBasicMaterial extends Material{ constructor(o){ super(o); this.unlit=true; } }
class LineBasicMaterial extends Material{ constructor(o){ super(o); this.unlit=true; } }
// ---- scene graph ----
class Object3D{ constructor(){ this.position=new Vector3(); this.quaternion=new Quaternion(); this.rotation=new Euler(); this.scale=new Vector3(1,1,1); this.children=[]; this.parent=null; this.visible=true; this.userData={}; this.matrixWorld=new Matrix4(); this.castShadow=false; this.receiveShadow=true; this._m=new Matrix4(); this._q=new Quaternion(); }
  add(o){ if(o.parent) o.parent.remove(o); o.parent=this; this.children.push(o); return this; } remove(o){ const i=this.children.indexOf(o); if(i>=0){ this.children.splice(i,1); o.parent=null; } return this; }
  updateWorld(parentM){ const r=this.rotation; let q=this.quaternion; if(r.x||r.y||r.z){ q=this._q.setFromEuler(r).premultiply(this.quaternion); } this._m.compose(this.position,q,this.scale); if(parentM) this.matrixWorld.multiplyMatrices(parentM,this._m); else this.matrixWorld.copy(this._m); for(const c of this.children) c.updateWorld(this.matrixWorld); }
  getWorldPosition(v){ v=v||new Vector3(); const e=this.matrixWorld.e; return v.set(e[12],e[13],e[14]); }
  lookAt(t){ const z=this.position.clone().sub(t).normalize(); if(z.length()<1e-6) z.set(0,0,1); const up=new Vector3(0,1,0); if(Math.abs(z.dot(up))>0.9999) up.set(0,0,1); const x=new Vector3().crossVectors(up,z).normalize(); const y=new Vector3().crossVectors(z,x);
    const m00=x.x,m01=y.x,m02=z.x,m10=x.y,m11=y.y,m12=z.y,m20=x.z,m21=y.z,m22=z.z; const tr=m00+m11+m22; let qx,qy,qz,qw;
    if(tr>0){ const s=.5/Math.sqrt(tr+1); qw=.25/s; qx=(m21-m12)*s; qy=(m02-m20)*s; qz=(m10-m01)*s; }
    else if(m00>m11&&m00>m22){ const s=2*Math.sqrt(1+m00-m11-m22); qw=(m21-m12)/s; qx=.25*s; qy=(m01+m10)/s; qz=(m02+m20)/s; }
    else if(m11>m22){ const s=2*Math.sqrt(1+m11-m00-m22); qw=(m02-m20)/s; qx=(m01+m10)/s; qy=.25*s; qz=(m12+m21)/s; }
    else { const s=2*Math.sqrt(1+m22-m00-m11); qw=(m10-m01)/s; qx=(m02+m20)/s; qy=(m12+m21)/s; qz=.25*s; }
    this.quaternion.set(qx,qy,qz,qw); this.rotation.set(0,0,0); return this; } }
class Group extends Object3D{}
class Mesh extends Object3D{ constructor(geo,mat){ super(); this.geometry=geo; this.material=mat; } }
class LineSegments extends Mesh{}
class PerspectiveCamera extends Object3D{ constructor(fov,aspect,near,far){ super(); this.fov=fov; this.aspect=aspect; this.near=near; this.far=far; this.proj=new Matrix4(); this.view=new Matrix4(); this.updateProjectionMatrix(); } updateProjectionMatrix(){ this.proj.perspective(this.fov*Math.PI/180,this.aspect,this.near,this.far); }
  getWorldDirection(v){ const q=this.quaternion; return v.set(0,0,-1).applyQuaternion(q).normalize(); } }
class Light extends Object3D{ constructor(color,intensity){ super(); this.color=new Color(color); this.intensity=intensity; } }
class HemisphereLight extends Light{ constructor(sky,ground,i){ super(sky,i); this.groundColor=new Color(ground); } }
class DirectionalLight extends Light{ constructor(c,i){ super(c,i); this.target=new Object3D(); this.shadow={mapSize:{set(w,h){this.w=w;this.h=h;},w:2048,h:2048},camera:{left:-10,right:10,top:10,bottom:-10,near:1,far:60,updateProjectionMatrix(){}},bias:0.0005,normalBias:0.02}; } }
class PointLight extends Light{ constructor(c,i,dist){ super(c,i); this.distance=dist||10; } }
class FogExp2{ constructor(c,d){ this.color=new Color(c); this.density=d; } }
class Scene extends Object3D{ constructor(){ super(); this.fog=null; } }
// ---- renderer ----
const VS=`#version 300 es
precision highp float; layout(location=0) in vec3 p; layout(location=1) in vec3 n;
uniform mat4 uM,uV,uP,uL; out vec3 vN; out vec3 vW; out vec4 vL;
void main(){ vec4 w=uM*vec4(p,1.0); vW=w.xyz; vN=normalize(mat3(uM)*n); vL=uL*w; gl_Position=uP*uV*w; }`;
const FS=`#version 300 es
precision highp float; in vec3 vN; in vec3 vW; in vec4 vL; out vec4 o;
uniform vec3 uColor,uSide,uEmis,uCam,uSunDir,uSunCol,uHemiSky,uHemiGnd,uFogCol; uniform float uRough,uMetal,uOpac,uFog,uUnlit,uHasSide,uShadowOn,uBias;
uniform vec3 uPLpos[4]; uniform vec3 uPLcol[4]; uniform float uPLdist[4]; uniform int uNPL; uniform sampler2D uShadow;
float shadow(vec3 N){ if(uShadowOn<0.5) return 1.0; vec3 c=vL.xyz/vL.w*0.5+0.5; if(c.x<0.0||c.x>1.0||c.y<0.0||c.y>1.0||c.z>1.0) return 1.0; float b=uBias*(1.0+ (1.0-max(dot(N,uSunDir),0.0))*2.0); float s=0.0; vec2 ts=1.0/vec2(textureSize(uShadow,0));
  for(int x=-1;x<=1;x++)for(int y=-1;y<=1;y++){ float d=texture(uShadow,c.xy+vec2(x,y)*ts*1.2).r; s+= (c.z-b>d)?0.0:1.0; } return s/9.0; }
void main(){ vec3 N=normalize(vN); vec3 base=(uHasSide>0.5 && N.y<0.5)?uSide:uColor; vec3 col;
  if(uUnlit>0.5){ col=base; } else {
    vec3 V=normalize(uCam-vW); float sh=shadow(N);
    float hemi=N.y*0.5+0.5; vec3 amb=mix(uHemiGnd,uHemiSky,hemi)*base;
    float nl=max(dot(N,uSunDir),0.0); vec3 H=normalize(uSunDir+V); float spec=pow(max(dot(N,H),0.0),mix(8.0,96.0,1.0-uRough))*(0.15+uMetal*0.6);
    col=amb+ (base*nl + uSunCol*spec*nl)*uSunCol*sh;
    for(int i=0;i<4;i++){ if(i>=uNPL) break; vec3 d=uPLpos[i]-vW; float dist=length(d); d/=dist; float att=clamp(1.0-dist/uPLdist[i],0.0,1.0); att*=att; col+=base*uPLcol[i]*max(dot(N,d),0.0)*att; }
    float fres=pow(1.0-max(dot(N,V),0.0),3.0); col+=uHemiSky*fres*0.12; col+=uEmis; }
  if(uFog>0.0){ float f=1.0-exp(-uFog*uFog*dot(vW-uCam,vW-uCam)); col=mix(col,uFogCol,clamp(f,0.0,1.0)); }
  col*=0.85; col=(col*(2.51*col+0.03))/(col*(2.43*col+0.59)+0.14); col=pow(clamp(col,0.0,1.0),vec3(1.0/2.2)); o=vec4(col,uOpac); }`;
const DVS=`#version 300 es
precision highp float; layout(location=0) in vec3 p; uniform mat4 uM,uL; void main(){ gl_Position=uL*uM*vec4(p,1.0); }`;
const DFS=`#version 300 es
precision highp float; out vec4 o; void main(){ o=vec4(1.0); }`;
class WebGLRenderer{ constructor(o={}){ const cv=document.createElement('canvas'); this.domElement=cv; const gl=cv.getContext('webgl2',{antialias:o.antialias!==false,alpha:o.alpha!==false,premultipliedAlpha:false}); if(!gl) throw new Error('WebGL2 not available'); this.gl=gl; this.pr=1; this.shadowMap={enabled:true}; this.prog=this._prog(VS,FS); this.dprog=this._prog(DVS,DFS); this.u={}; const P=this.prog; gl.useProgram(P); ['uM','uV','uP','uL','uColor','uSide','uEmis','uCam','uSunDir','uSunCol','uHemiSky','uHemiGnd','uFogCol','uRough','uMetal','uOpac','uFog','uUnlit','uHasSide','uShadowOn','uBias','uNPL','uShadow'].forEach(n=>this.u[n]=gl.getUniformLocation(P,n)); for(let i=0;i<4;i++){ this.u['uPLpos'+i]=gl.getUniformLocation(P,`uPLpos[${i}]`); this.u['uPLcol'+i]=gl.getUniformLocation(P,`uPLcol[${i}]`); this.u['uPLdist'+i]=gl.getUniformLocation(P,`uPLdist[${i}]`);} this.du={uM:gl.getUniformLocation(this.dprog,'uM'),uL:gl.getUniformLocation(this.dprog,'uL')};
    this.shadowSize=2048; this._initShadow(); this.lightMat=new Matrix4(); this.setSize(innerWidth,innerHeight); }
  _prog(vs,fs){ const gl=this.gl; const mk=(t,s)=>{ const sh=gl.createShader(t); gl.shaderSource(sh,s); gl.compileShader(sh); if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS)) throw new Error(gl.getShaderInfoLog(sh)); return sh; }; const p=gl.createProgram(); gl.attachShader(p,mk(gl.VERTEX_SHADER,vs)); gl.attachShader(p,mk(gl.FRAGMENT_SHADER,fs)); gl.linkProgram(p); if(!gl.getProgramParameter(p,gl.LINK_STATUS)) throw new Error(gl.getProgramInfoLog(p)); return p; }
  _initShadow(){ const gl=this.gl,S=this.shadowSize; this.shadowTex=gl.createTexture(); gl.bindTexture(gl.TEXTURE_2D,this.shadowTex); gl.texImage2D(gl.TEXTURE_2D,0,gl.DEPTH_COMPONENT24,S,S,0,gl.DEPTH_COMPONENT,gl.UNSIGNED_INT,null); gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST); gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST); gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE); gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE); this.fbo=gl.createFramebuffer(); gl.bindFramebuffer(gl.FRAMEBUFFER,this.fbo); gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.TEXTURE_2D,this.shadowTex,0); gl.drawBuffers([gl.NONE]); gl.readBuffer(gl.NONE); gl.bindFramebuffer(gl.FRAMEBUFFER,null); }
  setPixelRatio(r){ this.pr=r; } setSize(w,h){ this.w=w; this.h=h; const cv=this.domElement; cv.width=Math.round(w*this.pr); cv.height=Math.round(h*this.pr); cv.style.width=w+'px'; cv.style.height=h+'px'; }
  _geo(g){ const gl=this.gl; if(g._gl) return g._gl; const vao=gl.createVertexArray(); gl.bindVertexArray(vao); const vb=gl.createBuffer(); gl.bindBuffer(gl.ARRAY_BUFFER,vb); gl.bufferData(gl.ARRAY_BUFFER,g.pos,gl.STATIC_DRAW); gl.enableVertexAttribArray(0); gl.vertexAttribPointer(0,3,gl.FLOAT,false,0,0); if(g.nrm){ const nb=gl.createBuffer(); gl.bindBuffer(gl.ARRAY_BUFFER,nb); gl.bufferData(gl.ARRAY_BUFFER,g.nrm,gl.STATIC_DRAW); gl.enableVertexAttribArray(1); gl.vertexAttribPointer(1,3,gl.FLOAT,false,0,0);} else { gl.disableVertexAttribArray(1); gl.vertexAttrib3f(1,0,1,0);} let n=g.pos.length/3; if(g.idx){ const ib=gl.createBuffer(); gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib); gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,g.idx,gl.STATIC_DRAW); n=g.idx.length; } gl.bindVertexArray(null); g._gl={vao,n,indexed:!!g.idx,lines:g.lines}; return g._gl; }
  render(scene,camera){ const gl=this.gl; scene.updateWorld(null); camera.updateWorld(null); camera.view.copy(camera.matrixWorld).invert();
    const meshes=[],lights={hemi:null,sun:null,pts:[]}; const walk=o=>{ if(!o.visible) return; if(o instanceof Mesh) meshes.push(o); else if(o instanceof HemisphereLight) lights.hemi=o; else if(o instanceof DirectionalLight) lights.sun=o; else if(o instanceof PointLight) lights.pts.push(o); for(const c of o.children) walk(c); }; walk(scene);
    const camPos=camera.getWorldPosition(new Vector3());
    // shadow pass
    const sun=lights.sun; let sunDir=new Vector3(0,1,0);
    if(sun){ const sp=sun.getWorldPosition(new Vector3()); const tp=sun.target.getWorldPosition(new Vector3()); sunDir=sp.clone().sub(tp).normalize(); const sc=sun.shadow.camera; const view=new Matrix4().lookAt(sp,tp,new Vector3(0,1,0)); const proj=new Matrix4().ortho(sc.left,sc.right,sc.bottom,sc.top,sc.near,sc.far); this.lightMat.multiplyMatrices(proj,view);
      gl.bindFramebuffer(gl.FRAMEBUFFER,this.fbo); gl.viewport(0,0,this.shadowSize,this.shadowSize); gl.clearDepth(1); gl.clear(gl.DEPTH_BUFFER_BIT); gl.enable(gl.DEPTH_TEST); gl.depthMask(true); gl.disable(gl.BLEND); gl.enable(gl.CULL_FACE); gl.cullFace(gl.FRONT); gl.useProgram(this.dprog); gl.uniformMatrix4fv(this.du.uL,false,this.lightMat.e);
      for(const m of meshes){ if(!m.castShadow||m.geometry.lines||(m.material.transparent&&m.material.opacity<0.5)) continue; const g=this._geo(m.geometry); gl.uniformMatrix4fv(this.du.uM,false,m.matrixWorld.e); gl.bindVertexArray(g.vao); if(g.indexed) gl.drawElements(gl.TRIANGLES,g.n,gl.UNSIGNED_SHORT,0); else gl.drawArrays(gl.TRIANGLES,0,g.n); }
      gl.cullFace(gl.BACK); gl.bindFramebuffer(gl.FRAMEBUFFER,null); }
    // main pass
    gl.viewport(0,0,this.domElement.width,this.domElement.height); gl.clearColor(0,0,0,0); gl.clearDepth(1); gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT); gl.enable(gl.DEPTH_TEST); gl.enable(gl.CULL_FACE); gl.useProgram(this.prog); const u=this.u;
    gl.uniformMatrix4fv(u.uV,false,camera.view.e); gl.uniformMatrix4fv(u.uP,false,camera.proj.e); gl.uniformMatrix4fv(u.uL,false,this.lightMat.e); gl.uniform3f(u.uCam,camPos.x,camPos.y,camPos.z);
    gl.uniform3f(u.uSunDir,sunDir.x,sunDir.y,sunDir.z); const sc=sun?sun.color:new Color(0xffffff), si=sun?sun.intensity:1; gl.uniform3f(u.uSunCol,sc.r*si,sc.g*si,sc.b*si);
    const h=lights.hemi; gl.uniform3f(u.uHemiSky,...(h?[h.color.r*h.intensity,h.color.g*h.intensity,h.color.b*h.intensity]:[.4,.4,.4])); gl.uniform3f(u.uHemiGnd,...(h?[h.groundColor.r*h.intensity,h.groundColor.g*h.intensity,h.groundColor.b*h.intensity]:[.1,.1,.1]));
    const fog=scene.fog; gl.uniform1f(u.uFog,fog?fog.density:0); if(fog) gl.uniform3f(u.uFogCol,fog.color.r,fog.color.g,fog.color.b);
    gl.uniform1f(u.uShadowOn,sun&&this.shadowMap.enabled?1:0); gl.uniform1f(u.uBias,sun?sun.shadow.bias:0.001); gl.activeTexture(gl.TEXTURE0); gl.bindTexture(gl.TEXTURE_2D,this.shadowTex); gl.uniform1i(u.uShadow,0);
    const pts=lights.pts.slice(0,4); gl.uniform1i(u.uNPL,pts.length); pts.forEach((p,i)=>{ const wp=p.getWorldPosition(new Vector3()); gl.uniform3f(u['uPLpos'+i],wp.x,wp.y,wp.z); gl.uniform3f(u['uPLcol'+i],p.color.r*p.intensity,p.color.g*p.intensity,p.color.b*p.intensity); gl.uniform1f(u['uPLdist'+i],p.distance); });
    const opaque=[],trans=[]; for(const m of meshes){ (m.material.transparent||m.geometry.lines)?trans.push(m):opaque.push(m); }
    trans.forEach(m=>{ m._d=m.getWorldPosition(new Vector3()).distanceTo(camPos); }); trans.sort((a,b)=>b._d-a._d);
    const draw=m=>{ const mt=m.material; const g=this._geo(m.geometry); gl.uniformMatrix4fv(u.uM,false,m.matrixWorld.e); gl.uniform3f(u.uColor,mt.color.r,mt.color.g,mt.color.b); gl.uniform1f(u.uHasSide,mt.sideColor?1:0); if(mt.sideColor) gl.uniform3f(u.uSide,mt.sideColor.r,mt.sideColor.g,mt.sideColor.b); const ei=mt.emissiveIntensity; gl.uniform3f(u.uEmis,mt.emissive.r*ei,mt.emissive.g*ei,mt.emissive.b*ei); gl.uniform1f(u.uRough,mt.roughness); gl.uniform1f(u.uMetal,mt.metalness); gl.uniform1f(u.uOpac,mt.opacity); gl.uniform1f(u.uUnlit,mt.unlit?1:0); gl.bindVertexArray(g.vao); if(g.lines) gl.drawArrays(gl.LINES,0,g.n); else if(g.indexed) gl.drawElements(gl.TRIANGLES,g.n,gl.UNSIGNED_SHORT,0); else gl.drawArrays(gl.TRIANGLES,0,g.n); };
    gl.disable(gl.BLEND); gl.depthMask(true); opaque.forEach(draw);
    gl.enable(gl.BLEND); gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA); trans.forEach(m=>{ gl.depthMask(!!m.material.depthWrite && !m.geometry.lines); draw(m); }); gl.depthMask(true); gl.bindVertexArray(null); }
}
return {Vector3,Quaternion,Euler,Matrix4,Color,BufferGeometry,BoxGeometry:function(w,h,d){return buildBox((w??1)/2,(h??1)/2,(d??1)/2);},EdgesGeometry:function(g){return EdgesGeometry_(g);},CylinderGeometry:function(a,b,c,d){return CylinderGeometry_(a,b,c,d);},TorusGeometry:function(a,b,c,d){return TorusGeometry_(a,b,c,d);},OctahedronGeometry:function(r){return OctahedronGeometry_(r);},PlaneGeometry:function(w,h){return PlaneGeometry_(w,h);},Material,MeshStandardMaterial,MeshBasicMaterial,LineBasicMaterial,Object3D,Group,Mesh,LineSegments,PerspectiveCamera,HemisphereLight,DirectionalLight,PointLight,FogExp2,Scene,WebGLRenderer};
})();
